### ISSUE TITLE
femboy theme

### ISSUE THREAD

**Issue by CubeyTheCube** [MESYETI/yedit-7#2]
femboy theme

**Comment by CubeyTheCube** [comment]
com img femboy.png

**Comment by MESYETI** [comment]
no

**Comment by CubeyTheCube** [comment]
@MESYETI tr-ed has femboy theme, im moving to tr-ed, yedit fucking sucks, yedit is for fucking commie pinko fascist left wing alt-right radical front back up down stupid poopy fart butt heads
